# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(782, 461)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #2f2f2f;\n"
"    color: #f0f0f0;\n"
"}\n"
"\n"
"QMenuBar {\n"
"    background-color: #3d3d3d;\n"
"    color: #f0f0f0;\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background-color: #444444;\n"
"}\n"
"\n"
"QMenu {\n"
"    background-color: #3d3d3d;\n"
"    color: #f0f0f0;\n"
"    border: 1px solid #444444;\n"
"}\n"
"\n"
"QMenu::item {\n"
"    padding: 4px 24px;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: #444444;\n"
"}\n"
"\n"
"QToolBar {\n"
"    background-color: #3d3d3d;\n"
"    border: 1px solid #444444;\n"
"    spacing: 3px;\n"
"}\n"
"\n"
"QToolBar::separator {\n"
"    background-color: #444444;\n"
"}\n"
"\n"
"QPushButton {\n"
"    color: #f0f0f0;\n"
"    background-color: #444444;\n"
"    border: none;\n"
"    padding: 4px 16px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3d3d3d;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    color: #f0f0f0;\n"
"    background-color: #444444;\n"
"    padding: 2px;\n"
"    border: none;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #f0f0f0;\n"
"    background-color: #2f2f2f;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    background-color: #3d3d3d;\n"
"    color: #f0f0f0;\n"
"    alternate-background-color: #444444;\n"
"    gridline-color: #444444;\n"
"}\n"
"\n"
"QHeaderView {\n"
"    background-color: #3d3d3d;\n"
"    color: #f0f0f0;\n"
"    border: none;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #2f2f2f;\n"
"    color: #f0f0f0;\n"
"    padding: 4px 8px;\n"
"    border: none;\n"
"}\n"
"\n"
"QHeaderView::section:checked {\n"
"    background-color: #444444;\n"
"}\n"
"\n"
"QHeaderView::section:hover {\n"
"    background-color: #444444;\n"
"}\n"
"\n"
"QComboBox {\n"
"    color: #f0f0f0;\n"
"    background-color: #444444;\n"
"    border: none;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    background-color: #3d3d3d;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 24px;\n"
"    border-left-width: 1px;\n"
"    border-left-color: #444444;\n"
"    border-left-style: solid;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(down_arrow.png);\n"
"    width: 16px;\n"
"    height: 16px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter = QtWidgets.QSplitter(parent=self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        self.splitter_2 = QtWidgets.QSplitter(parent=self.splitter)
        self.splitter_2.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.layoutWidget = QtWidgets.QWidget(parent=self.splitter_2)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox = QtWidgets.QComboBox(parent=self.layoutWidget)
        self.comboBox.setMinimumSize(QtCore.QSize(80, 30))
        self.comboBox.setMaximumSize(QtCore.QSize(16777215, 30))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.line_2 = QtWidgets.QFrame(parent=self.layoutWidget)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit.setMinimumSize(QtCore.QSize(240, 30))
        self.lineEdit.setFrame(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.line = QtWidgets.QFrame(parent=self.layoutWidget)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.search_Button = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.search_Button.setMinimumSize(QtCore.QSize(75, 30))
        self.search_Button.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.search_Button.setFont(font)
        self.search_Button.setObjectName("search_Button")
        self.horizontalLayout.addWidget(self.search_Button)
        self.gridLayout_2.addWidget(self.splitter, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(168, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.drawing_Button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.drawing_Button.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.drawing_Button.setFont(font)
        self.drawing_Button.setObjectName("drawing_Button")
        self.gridLayout_2.addWidget(self.drawing_Button, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setLineWidth(1)
        self.frame.setMidLineWidth(1)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.frame)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox.setItemText(1, _translate("MainWindow", "苗栗縣"))
        self.comboBox.setItemText(2, _translate("MainWindow", "連江縣"))
        self.comboBox.setItemText(3, _translate("MainWindow", "彰化縣"))
        self.comboBox.setItemText(4, _translate("MainWindow", "雲林縣"))
        self.comboBox.setItemText(5, _translate("MainWindow", "金門縣"))
        self.comboBox.setItemText(6, _translate("MainWindow", "澎湖縣"))
        self.comboBox.setItemText(7, _translate("MainWindow", "嘉義縣"))
        self.comboBox.setItemText(8, _translate("MainWindow", "南投縣"))
        self.comboBox.setItemText(9, _translate("MainWindow", "臺東縣"))
        self.comboBox.setItemText(10, _translate("MainWindow", "屏東縣"))
        self.comboBox.setItemText(11, _translate("MainWindow", "花蓮縣"))
        self.comboBox.setItemText(12, _translate("MainWindow", "宜蘭縣"))
        self.comboBox.setItemText(13, _translate("MainWindow", "新竹縣"))
        self.comboBox.setItemText(14, _translate("MainWindow", "基隆市"))
        self.comboBox.setItemText(15, _translate("MainWindow", "新竹市"))
        self.comboBox.setItemText(16, _translate("MainWindow", "新北市"))
        self.comboBox.setItemText(17, _translate("MainWindow", "桃園市"))
        self.comboBox.setItemText(18, _translate("MainWindow", "臺北市"))
        self.comboBox.setItemText(19, _translate("MainWindow", "臺中市"))
        self.comboBox.setItemText(20, _translate("MainWindow", "臺南市"))
        self.comboBox.setItemText(21, _translate("MainWindow", "高雄市"))
        self.comboBox.setItemText(22, _translate("MainWindow", "嘉義市"))
        self.search_Button.setText(_translate("MainWindow", "搜尋"))
        self.drawing_Button.setText(_translate("MainWindow", "繪圖"))
